import type { Course } from '@/interfaces/course'

export const data: Array<Course> = [
  {
    id: 1,
    cover: '/images/courses/legitimacion.jfif',
    title: 'Prevención de Legitimación de Capitales',
    rating: 5,
    ratingCount: 8,
    price: 25,
    category: 'Beginner',
  },
  {
    id: 2,
    cover: '/images/courses/terrorismo.jpg',
    title: 'Prevención del Financiamiento al Terrorismo',
    rating: 5,
    ratingCount: 15,
    price: 20,
    category: 'Intermediate',
  },
  {
    id: 3,
    cover: '/images/courses/fraude.webp',
    title: 'Prevención de Fraude',
    rating: 4,
    ratingCount: 7,
    price: 30,
    category: 'Beginner',
  },
  {
    id: 4,
    cover: '/images/courses/corrupcion.jfif',
    title: 'Prevención de Corrupción',
    rating: 4,
    ratingCount: 12,
    price: 30,
    category: 'Intermediate',
  },
  {
    id: 5,
    cover: '/images/courses/destruccion.jfif',
    title: 'Prevención Financiamiento de la Proliferación de Armas de Destrucción Masiva',
    rating: 4,
    ratingCount: 32,
    price: 35,
    category: 'Intermediate',
  },
  {
    id: 6,
    cover: '/images/courses/capacitacion.jpg',
    title: 'Programas de Capacitación y Formación',
    rating: 5,
    ratingCount: 14,
    price: 35,
    category: 'Beginner',
  },
]
